# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:cran/ffmpeg-3
  - sudo apt-get -q update
  - sudo apt-get -y install libavfilter-dev libudunits2-dev libgdal1-dev libproj-dev libgeos-dev libarchive-dev
